### PR TITLE
Standard Website with all things covered.

### PR DESCRIPTION
**Pull request by xmyoard**
First of all, I want to say something:

1. The Image I added is a random image, so you can change it after some time.
2. The Font used here is "Roboto" which is a nice and open-source font by Google
3. All things you said are covered at the top of the page.
4. Given a detailed review of your powerful Discord Bots.
5. Hard-Codded by me, only fonts and style are taken from a library.
As said, the image can be changed.

And Before you merge the changes you can check it here:
https://aadi-mone.github.io/Alex0622.github.io/

And I have a doubt regarding the Github forking, as I saw some updates in your repo, but the updates are not coming in my fork, is that an error or do we need to fork again to update the resources?
 
thanking you,
Adarsh

### CODE REVIEW

**Comment by Alex22sv** [comment]
> And I have a doubt regarding the Github forking, as I saw some updates in your repo, but the updates are not coming in my fork, is that an error or do we need to fork again to update the resources?

AFAIK you'd need to fork again.

**Comment by Alex22sv** [comment]
By the way, found this in your code.
image

**Comment by xmyoard** [comment]
> By the way, found this in your code. image
I forgot to add the CSS for animation and parallax 😅

**Comment by Alex22sv** [comment]
And are you able to fix that?, if not I would revert the changes.

**Comment by xmyoard** [comment]
Yes, those big errors were fixed

These are some common errors made by Chrome, and AFIK it can't be fixed, and Every site has some errors like this, I am now working on the Big error, after that I will again open a pull request. 
thanking you,
Adarsh

**Pull request merged**
