### PR TITLE
Error with CSS fixed.

### PR DESCRIPTION
**Pull request by xmyoard**
I have fixed the errors in the HTML and there are some common errors but not with us or the site.
And Is there anything I missed, then please let me know, so I can change that.
The rest of all is fixed.

Thanks and have a nice day!

### CODE REVIEW

**Comment by Alex22sv** [comment]
Well, as far as I remember that's pretty all, although I'd suggest to keep using a script and style file to have better organized the website, but that's up to you.

**Comment by Aadi-mone** [comment]
okay...?
CSS in Html is easy so we can change anything by editing the index page instead of going to the CSS page, and the scripts are from
AMP library, and it's not up to me it's up to you because you are the site owner.   
Is there anything else I can change or do?
or you can perform a merge?

thanking you,
Adarsh

**Comment by xmyoard** [comment]
okay...?
CSS in Html is easy so we can change anything by editing the index page instead of going to the CSS page, and the scripts are from
AMP library, and it's not up to me it's up to you because you are the site owner.
Is there anything else I can change or do?
or you can perform a merge?

thanking you,
Adarsh

**Comment by xmyoard** [comment]
uh is this pull request dead?

**Comment by Alex22sv** [comment]
I'll keep my changes, for now.

**Comment by Aadi-mone** [comment]
oh ok, thanks for letting me know,
is there anything else I can help with?

**Pull request closed without merging**
